website/auth.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)
@auth.route('/login', methods=['GET','POST'])
def login():
  if request.method == 'POST':
    email_user = request.form.get('email_user')
    password = request.form.get('password')

    user = User.query.filter_by(email=email_user).first()
    if user:
      if check_password_hash(user.password, password):
        flash('Logged in sucessfully!', category='success')
        if request.form.get('remember_me'):
          login_user(user, remember=True)
        else:
          login_user(user)
        return redirect(url_for('views.home'))
      else:
        flash('Incorrect password, please try again!', category='error')
    else: 
      user = User.query.filter_by(username=email_user).first()
      if user:
        if check_password_hash(user.password, password):
          flash('Logged in sucessfully!', category='success')
          if request.form.get('remember_me'):
            login_user(user, remember=True)
          else:
            login_user(user)
          return redirect(url_for('views.home'))
        else:
         flash('Incorrect password, please try again!', category='error')

      else:
        flash('User does not exist! Please check for any typos!', category='error')

  return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
  logout_user()
  return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
  if request.method == 'POST':
    username = request.form.get('username')
    email = request.form.get('email')
    password1 = request.form.get('password1')
    password2 = request.form.get('password2')
    accept = request.form.get('tcs')

    user = User.query.filter_by(email=email).first()
    name = User.query.filter_by(username=username).first()
    if name:
      flash('Username already taken!', category='error')
    else:
      if len(username) < 3:
        flash('Username must be more than 3 characters!', category='error')
      elif len(username) > 15:
        flash('Username exceeds character limit!', category='error')
      elif user:
        flash('Email already exists.', category='error')
      elif len(email) < 4:
        flash('Email must be more than 3 characters!', category='error')
      elif password1 != password2:
        flash('Passwords do not match!', category='error')
      elif len(password1) < 7:
        flash('Password must be greater than 7 characters!', category='error')
      elif not accept:
        flash('Please read our privacy policy and terms and conditions', category='error')

      else:
        new_user = User(username=username, email=email, password=generate_password_hash(password1, method='sha256'))
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user, remember=True)

        flash('Welcome to Libhub!', category='success')
        return redirect(url_for('views.home'))

  return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, url_for, flash, redirect, abort
from flask_login import login_required, current_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime, timedelta
from . import db
from .models import User, Borrowed_book, Book, Borrower, Lender


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
  """'
  This is my home page, users can search books here
  """
  if request.method == 'POST':
    term = request.form.get('search')
    
    return redirect(url_for('views.search', searchterm=term))

  return render_template("index.html", user=current_user)

@views.route('/termsandconditions')
def tandc():
  """
  This is my terms and conditions page
  """
  return render_template('tc.html')

@views.route('/privacypolicy')
def privacy():
  """
  This is my privacy policy page
  """
  return render_template('privacypolicy.html')

@views.route('/books')
def books():
  """
  This is my books page, it prints out the first 4 recently added books that current user does not own.
  """
  if current_user.is_authenticated is True:
    books = Book.query.filter(Book.lender_user_id != current_user.id)\
    .order_by(Book.created_on.desc()).limit(4).all()
  else:
    books = Book.query.order_by(Book.created_on).limit(4).all()
  return render_template("books.html", user=current_user, books=books)

@views.route('/search/<path:searchterm>')
def search(searchterm):
  """
  This is my search page, users redirect to this page once they've searched in the home page.
  """
  
  term = "%{}%".format(searchterm)

  search = Book.query.filter((Book.title.like(term)) | (Book.author.like(term)) | (Book.lender_username.like(term))).all()
  
  return render_template('search.html', user=current_user, results=search, searchterm=searchterm)


@views.route('/user/<int:userid>')
def user(userid):
  """
  This prints user information
  """

  user = User.query.get_or_404(userid)

  return render_template('user.html', userdetails=user, user=current_user)


@views.route('/dashboard/<int:user_id>', methods=['GET', 'POST'])
@login_required
def dashboard(user_id):
  """
  This is the base dashboard page, users must be logged in to access
  """

  if current_user.id != user_id:
    abort(403)

  user = User.query.filter_by(id=user_id).first()

  return render_template("dashboard/dashboard.html", user=user)

@views.route('/dashboard/booksborrowed/<int:user_id>')
@login_required
def borrowed(user_id):
  """
  This is borrowed page, it takes the current user id and checks if they have books borrowed under their account and prints it out on the page.
  """
  if current_user.id != user_id:
    abort(403)

  borrower = Borrower.query.filter_by(user_id=user_id).first()

  if not borrower:
    flash('Enter personal details!', category='error')
    return redirect(url_for('views.infoedit', user_id=current_user.id))
  else:
    bookslist = db.session.query(Borrowed_book, Book)\
      .filter(Borrowed_book.borrower_id == borrower.id)\
      .filter(Borrowed_book.return_confirm == False)\
      .outerjoin(Borrowed_book, Borrowed_book.book_id == Book.id)\
      .add_columns(Book.id, Book.lender_user_id, Borrowed_book.due_date, Borrowed_book.return_book, Borrowed_book.return_confirm, Book.title, Book.author, Book.lender_username, Borrowed_book.lender_confirm, Borrowed_book.lender_id)\
      .filter(Book.id == Borrowed_book.book_id).all()

  datenow = datetime.today()

  return render_template("dashboard/booksborrowed.html", user=current_user, bookslist=bookslist, datenow=datenow)

@views.route('/dashboard/bookslended/<int:user_id>')
@login_required
def lended(user_id):
  """
  This is my lended page, it takes the current user id and checks if they have books that they've lended on the system and it prints it out on the page. 
  """

  if current_user.id != user_id:
    abort(403)

  books = Book.query.filter_by(lender_user_id=user_id).all()

  return render_template("dashboard/bookslended.html", user=current_user, books=books)

@views.route('/dashboard/bookslended/bookstatus/<int:book_id>')
@login_required
def status(book_id):
  """
  This is my status page, it takes the book id that the user has lended and checks if anyone has requested or is currently borrowing that book. 
  """

  book = Book.query.get_or_404(book_id)


  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\
    .filter(Borrowed_book.return_confirm == False)\
    .outerjoin(Borrowed_book, Borrowed_book.borrower_id==Borrower.id)\
    .add_columns(Borrower.username, Borrower.id, Borrowed_book.borrower_id, Borrowed_book.lender_confirm, Borrowed_book.return_book)\
    .filter(Borrower.id == Borrowed_book.borrower_id)\
    .order_by(Borrowed_book.borrowed_date).all()
  
  if current_user.id != book.lender_user_id:
    abort(403)

  return render_template("dashboard/bookstatus.html", user=current_user, books=book, borrowerlist=borrowerlist)

@views.route('/deny/<int:book_id>/borrower/<int:borrower_id>', methods=['GET', 'POST'])
@login_required
def deny(book_id, borrower_id):
  """
  This allows the lender to deny a user to borrow a book.
  """
  book = Book.query.get_or_404(book_id)

  requests = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\
    .filter(borrower_id == Borrowed_book.borrower_id)\
    .outerjoin(Borrower, Borrower.id==Borrowed_book.borrower_id)\
    .add_columns(Borrower.username, Borrower.id, Borrowed_book.borrower_id, Borrower.fName, Borrower.lName, Borrower.address1, Borrower.city, Borrower.phone, Borrowed_book.lender_confirm)\
    .filter(Borrower.id == Borrowed_book.borrower_id).first()

  if current_user.id != book.lender_user_id:
    abort(403)


  else:
    if request.method == 'POST':
      for borrower in borrowerlist:
        borrower = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

      accept = request.form.get('tcs')

      if borrower.lender_confirm:
        flash('Book already being borrowed.', category='error')
        return redirect(url_for('views.status', book_id=book_id))    

      elif not accept:
        flash('Please read and accept our terms and conditions!', category='error')

      else:
        db.session.delete(requests)
        db.session.commit()

        flash('Successfully deleted! Now returning to dashboard', category='success')
        return redirect(url_for('views.status', book_id=book_id))    

  return render_template("deny.html", user=current_user, book=book, borrowerlist=borrowerlist)



@views.route('/accept/<int:book_id>/borrower/<int:borrower_id>', methods=['GET', 'POST'])
@login_required
def accept(book_id, borrower_id):
  """
  This allows the lender to accept requests, it sets the due date to weeks from hitting the accept button on this page. 
  """
  book = Book.query.get_or_404(book_id)

  requests = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\
    .filter(borrower_id == Borrowed_book.borrower_id)\
    .outerjoin(Borrower, Borrower.id==Borrowed_book.borrower_id)\
    .add_columns(Borrower.username, Borrower.id, Borrowed_book.borrower_id, Borrower.fName, Borrower.lName, Borrower.address1, Borrower.city, Borrower.phone, Borrowed_book.lender_confirm)\
    .filter(Borrower.id == Borrowed_book.borrower_id).first()

  borrower_exists = db.session.query(Borrower, Borrowed_book)\
    .filter(borrower_id == Borrowed_book.borrower_id)\
    .filter(Borrowed_book.lender_confirm == True)\
    .outerjoin(Borrower, Borrower.id==Borrowed_book.borrower_id)\
    .filter(Borrower.id == Borrowed_book.borrower_id).first()

  if current_user.id != book.lender_user_id:
    abort(403)


  else:
    if request.method == 'POST':
      for borrower in borrowerlist:
        borrower = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

      accept = request.form.get('tcs')

      if borrower.lender_confirm:
        flash('Book already being borrowed.', category='error')
        return redirect(url_for('views.status', book_id=book_id))    

      elif borrower_exists:
        flash('Borrower is already at limit (1/1)', category='error')
        return redirect(url_for('views.status', book_id=book_id))    


      elif not accept:
        flash('Please read and accept our terms and conditions!', category='error')

      else:

        requests.lender_confirm = True
        
        requests.borrowed_date = datetime.utcnow()
        
        due_date_set = timedelta(weeks = 2)
        due_date = datetime.utcnow() + due_date_set

        requests.due_date = due_date

        db.session.add(requests)
        db.session.commit()

        flash('Successfully confirmed! Now returning to dashboard', category='success')
        return redirect(url_for('views.status', book_id=book_id))    


  return render_template("accept.html", user=current_user, book=book, borrowerlist=borrowerlist, borrower_exists=borrower_exists)

@views.route('/returned/<int:book_id>/borrower/<int:borrower_id>', methods=['GET', 'POST'])
@login_required
def return_confirm(book_id, borrower_id):
  """
  This allows the lender to confirm that the borrower has returned the book
  """
  book = Book.query.get_or_404(book_id)

  requests = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\

website/templates/accept.html
{% extends "base.html" %} {% block title %}Accept Borrower for {{book.title}}{% endblock %}{% block content
  %} 
  <div class="container-fluid bg-dark w-100 h-100 d-grid position-absolute top-0 start-0 overflow-hidden">
    <div class="row row-cols-2 align-items-center ">
      <div class="col-sm-4">
        <div class="row row-cols-1 justify-content-center">
          <h1 class="text-center pb-3 text-light">Borrowing:</h1>
          <div class="card col-mb-4 p-0" style="width: 18rem;">
            <img src="/static/images/book.jpg" class="card-img-top" alt="book">
            <div class="card-body">
              <h5 class="card-title"> {{ book.title }} </h5>
              <h6 class="card-subtitle mb-2"> {{ book.author }} </h6>
              <h6 class="card-subtitle"> Due date will be two weeks after today. </h6>
            </div>
          </div>
          {% if not borrower_exists %}
            <a class="text-decoration-none" href="{{ url_for('views.status', book_id=book.id) }}">
              <button class="btn btn-md btn-secondary w-50 d-flex justify-content-center align-items-center mt-5 mx-auto">Return</button>
            </a>     
          {%endif%}

        </div>
      </div>
      <div class="col-sm-8 p-3">
        <main class="text-center px-4 py-4 m-auto">
          <form method="POST">
            <div class="row row-cols-2 gy-3">
              <div class="col-6 offset-3">
                <img class="p-0 mb-2" src="/static/images/Libhub-2.svg" alt="logo">
                <h1 class="h3 fw-semibold text-light">Borrower Details</h1>
                {%if borrower_exists%}
                <p class="mb-3 fw-light text-warning">Borrower  <a class="text-decoration-none text-primary" href="{{url_for('views.user', userid=borrowerlist.id)}}">({{borrowerlist.username}})</a> already at limit (1/1). Borrower cannot borrower any books!</p>
                {%else%}
                <p class="mb-3 fw-light text-muted">Borrower <a class="text-decoration-none text-secondary" href="{{url_for('views.user', userid=borrowerlist.id)}}">({{borrowerlist.username}})</a> will immediately be notifed and will be sent any necessary details.</p>
                {%endif%}

              </div>

              <div class="col-4 offset-2">
                <h3 class="fs-5 text-white-50">First Name:</h3>
                <h5 class="fs-6 text-white">{{borrowerlist.fName}}</h5>
              </div>

              <div class="col-4">
                <h3 class="fs-5 text-white-50">Last Name:</h3>
                <h5 class="fs-6 text-white">{{borrowerlist.lName}}</h5>
              </div>
        
              <div class="col-4 offset-2">
                <h3 class="fs-5 text-white-50">Address:</h3>
                <h5 class="fs-6 text-white">{{borrowerlist.address1}}</h5>
              </div>

              <div class="col-4 mb-3">
                <h3 class="fs-5 text-white-50">City:</h3>
                <h5 class="fs-6 text-white">{{borrowerlist.city}}</h5>
              </div>

              <div class="col-8 offset-2">
                <h3 class="fs-5 text-white-50">Phone Number:</h3>
                <h5 class="fs-6 text-white">0{{borrowerlist.phone}}</h5>
              </div>

              <div class="col-8 offset-2">
                  <p class="mt-3 text-center text-light fs-6">It is your reponsibilty to contact and deliver the book to the borrower to an mutually agreed meeting point. Any problems or issues after the borrowing phase will not under Libhub's&trade; control nor anyone affiliated with the brand. <strong>Failure to lend may lead to a temporary or permanent ban to your account.</strong></p>
              </div>

              <div class="col-4 offset-4">
                <input type="checkbox" value="checked" name="tcs">
                <label class="text-white">Agree to  <a class="text-decoration-underline text-secondary" href="{{url_for('views.tandc')}}" target="_blank" data-bs-toggle="" data-bs-placement="right" title="Open Terms and Conditions">terms and conditions</a></label>  
              </div>

              {%if borrower_exists%}
              <div class="col-4 offset-4">
                <div class="mt-2">
                  <a class="text-decoration-none" href="{{ url_for('views.status', book_id=book.id) }}">
                    <button class="btn btn-md btn-warning w-100">Return</button>
                  </a>         
                </div>
              {%else%}
              <div class="col-4 offset-4">
                <div class="mt-2">
                  <button class="btn btn-lg btn-primary w-100" type="submit">Accept Borrower</button>
                </div>
              {%endif%}
                
              </div>
            </div>
          </form>
        </main>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
      crossorigin="anonymous">
      
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
     />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <link href="{{ url_for('static', filename='css/style.scss.css') }}"
    rel="stylesheet" type="text/css">
    <link rel="icon" type="image/x-icon" href="/static/images/logo.svg">

    <title>{% block title %}{% endblock %}</title>
  </head>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark">

    <div class="container-fluid">

      <a href="{{ url_for('views.home') }}">
        <img src="/static/images/banner.svg" alt="logo-banner" class="navbar-brand ms-4 ">
      </a> 

      <button
        class="navbar-toggler me-4"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
        id="nav_button"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      {% if user.is_authenticated %}
      <div id="navbarNav" class="collapse navbar-collapse">
        <ul class="navbar navbar-nav bg-text-shadow me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link text-light fw-normal" href="{{ url_for('views.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light fw-normal" href="{{ url_for('views.books') }}">Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light fw-normal" href="{{ url_for('views.lend') }}">Lend</a>
          </li>
        </ul>
        <div class="navbar navbar-nav pe-lg-4 px-sm-4 mb-sm-0">

          <a href="{{ url_for('views.account', user_id=current_user.id) }}" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Account Settings">
            <i class="bi bi-person-circle px-3 pb-1 text-center" style="font-size: 1.75rem; color: #c9ddff;"></i>
          </a>

          <a class="nav-link text-primary fw-normal me-lg-3" href="{{ url_for('views.dashboard', user_id=current_user.id) }}" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Dashboard">{{user.username}}</a>

          <button type="button" class="nav-item btn btn-secondary navbar-btn btn-sm" onclick="window.location.href='/logout'" tabindex=0>Logout</button>
        </div>
      </div>

      {% else %}
      <div id="navbarNav" class="collapse navbar-collapse">
        <ul class="navbar navbar-nav bg-text-shadow me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link text-light fw-normal" href="{{ url_for('views.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light fw-normal" href="{{ url_for('views.books') }}">Books</a>
          </li>
        </ul> 
        <div class="navbar navbar-nav d-flex align-items-center justify-content-center pe-4">
          <button type="button" class="nav-item btn btn-link navbar-btn btn-sm px-3 me-1.5 text-decoration-none" onclick="window.location.href='/login'" tabindex=0>Already have an account?</button>

          <button type="button" class="nav-item btn btn-secondary navbar-btn btn-sm text-capitalize" onclick="window.location.href='/sign-up'" tabindex=0>Sign Up for Free</button>
        </div>
      </div>
      {% endif %}
    </div>
  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable d-flex align-items-center fade show fixed-top" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
      {{ message }}
      
      <button type="button" class="btn-close position-absolute top-25 end-0 me-3" data-bs-dismiss="alert" aria-label="Close"></button>     
    </div>

    {% else %}
    <div class="alert alert-success alert-dismissable d-flex align-items-center fade show fixed-top" role="alert">

      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="me-2"
        id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </svg>
      {{ message }}

      <button type="button" class="btn-close position-absolute top-25 end-0 me-3" data-bs-dismiss="alert" aria-label="Close"></button> 
    </div>

    {% endif %}
    {% endfor %}
    {% endif %}
  {% endwith %}

  <section>{% block content %} {% endblock %}</section>

  <div class="container-fluid bg-dark">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top footer">
      <p class="col-md-4 mb-0 text-light">&copy; 2022 Libhub, Inc</p>
  
      <a href="#top" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none pt-sm-4 pt-lg-0">
        <img class="d-block mx-auto" src="/static/images/footer.svg" alt="logo" >
      </a>
  
      <ul class="nav col-md-4 justify-content-lg-end px-4">
        <li class="nav-item"><a href="{{url_for('views.home')}}" class="nav-link px-2 text-light">Home</a></li>
        <li class="nav-item"><a href="{{url_for('views.privacy')}}" target="_blank" class="nav-link px-2 text-light">Privacy</a></li>
        <li class="nav-item"><a href="{{url_for('views.tandc')}}" target="_blank" class="nav-link px-2 text-light">Terms of Use</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a href="{{url_for('views.user', userid=current_user.id)}}" class="nav-link px-2 text-light">User</a></li>
        {%endif%}
        <li class="nav-item"><a href="https://github.com/whoisyersinia/1.3-and-1.4-Assessment" target="_blank" class="nav-link px-2 text-light"><i class="bi bi-github" style="font-size: 1.10rem; padding-right: 0.5rem;"></i>Github</a></li>
      </ul>
    </footer>
  </div>
  

    <script 
    src="https://code.jquery.com/jquery-3.6.0.js"
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous">
    </script>

    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
    crossorigin="anonymous">
    </script>

    <script
    type="text/javascript"
    src="{{ url_for('static', filename='javascript/script.js') }}"
    ></script>

  <!-- Your MOm-->
</html>

website/templates/lend.html
{% extends "base.html" %} {% block title %}Sign-Up - Lend{% endblock %}{% block content
%}
  
  <div class="container-fluid bg-dark vh-100 w-100 d-flex justify-content-center align-content-center">
    <main class="text-center w-auto m-auto border border-light rounded-3 px-4 py-4 ">

      <form method="POST">
        <img class="p-0 mb-2" src="./static/images/Libhub-2.svg" alt="logo">
        <h1 class="h3 fw-semibold text-light">Enter Book Details</h1>
        <p class="fw-normal text-muted">Please enter details as accurately as possible <br>
        {% if current_user.details == True %}
        Books will use the personal information entered <br> before to edit please <a href="{{url_for('views.infoedit', user_id=current_user.id)}}"target="_blank">click</a>.</p>
        {%endif%}


        <div class="form-floating">
          <input name="title" type="text" class="form-control border border-3 border-info" id="floatingInput" placeholder="'Animal Farm'" value="{{ request.form['title'] }}">
          <label for="floatingInput">Title</label>
        </div>
  
        <div class="form-floating mt-4">
          <input name="author" type="text" class="form-control border border-3 border-info" id="floatingAuthor" placeholder="George Orwell" value="{{ request.form['author'] }}">
          <label for="floatingAuthor">Author</label>
        </div>

        <div class="mt-4">
          <input type="checkbox" value="checked" name="tcs">
          <label class="text-white">Agree to <a class="text-decoration-underline text-secondary" href="{{url_for('views.tandc')}}" target="_blank" data-bs-toggle="tooltip" data-bs-placement="right" title="Open Terms and Conditions">terms and conditions</a></label>  
        </div>

        <div class="mt-4">
          <button class="btn btn-lg btn-primary w-100" type="submit">Submit book</button>
        </div>
        <p class="mt-5 mb-3 text-muted text-center text-light">&copy; 2022</p>

      </div>
      </form>
    </main>
  </div>
  {% endblock %}