website/auth.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)
@auth.route('/login', methods=['GET','POST'])
def login():
  if request.method == 'POST':
    email_user = request.form.get('email_user')
    password = request.form.get('password')

    user = User.query.filter_by(email=email_user).first()
    if user:
      if check_password_hash(user.password, password):
        flash('Logged in sucessfully!', category='success')
        if request.form.get('remember_me'):
          login_user(user, remember=True)
        else:
          login_user(user)
        return redirect(url_for('views.home'))
      else:
        flash('Incorrect password, please try again!', category='error')
    else: 
      user = User.query.filter_by(username=email_user).first()
      if user:
        if check_password_hash(user.password, password):
          flash('Logged in sucessfully!', category='success')
          if request.form.get('remember_me'):
            login_user(user, remember=True)
          else:
            login_user(user)
          return redirect(url_for('views.home'))
        else:
         flash('Incorrect password, please try again!', category='error')

      else:
        flash('User does not exist! Please check for any typos!', category='error')

  return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
  logout_user()
  return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
  if request.method == 'POST':
    username = request.form.get('username')
    email = request.form.get('email')
    password1 = request.form.get('password1')
    password2 = request.form.get('password2')
    accept = request.form.get('tcs')

    user = User.query.filter_by(email=email).first()
    name = User.query.filter_by(username=username).first()
    if name:
      flash('Username already taken!', category='error')
    else:
      if len(username) < 3:
        flash('Username must be more than 3 characters!', category='error')
      elif len(username) > 15:
        flash('Username exceeds character limit!', category='error')
      elif user:
        flash('Email already exists.', category='error')
      elif len(email) < 4:
        flash('Email must be more than 3 characters!', category='error')
      elif password1 != password2:
        flash('Passwords do not match!', category='error')
      elif len(password1) < 7:
        flash('Password must be greater than 7 characters!', category='error')
      elif not accept:
        flash('Please read our privacy policy and terms and conditions', category='error')

      else:
        new_user = User(username=username, email=email, password=generate_password_hash(password1, method='sha256'))
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user, remember=True)

        flash('Welcome to Libhub!', category='success')
        return redirect(url_for('views.home'))

  return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, url_for, flash, redirect, abort
from flask_login import login_required, current_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime, timedelta
from . import db
from .models import User, Borrowed_book, Book, Borrower, Lender


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
  """'
  This is my home page, users can search books here
  """
  if request.method == 'POST':
    term = request.form.get('search')
    
    return redirect(url_for('views.search', searchterm=term))

  return render_template("index.html", user=current_user)

@views.route('/termsandconditions')
def tandc():
  """
  This is my terms and conditions page
  """
  return render_template('tc.html')

@views.route('/privacypolicy')
def privacy():
  """
  This is my privacy policy page
  """
  return render_template('privacypolicy.html')

@views.route('/books')
def books():
  """
  This is my books page, it prints out the first 4 recently added books that current user does not own.
  """
  if current_user.is_authenticated is True:
    books = Book.query.filter(Book.lender_user_id != current_user.id)\
    .order_by(Book.created_on.desc()).limit(4).all()
  else:
    books = Book.query.order_by(Book.created_on).limit(4).all()
  return render_template("books.html", user=current_user, books=books)

@views.route('/search/<path:searchterm>')
def search(searchterm):
  """
  This is my search page, users redirect to this page once they've searched in the home page.
  """
  
  term = "%{}%".format(searchterm)

  search = Book.query.filter((Book.title.like(term)) | (Book.author.like(term)) | (Book.lender_username.like(term))).all()
  
  return render_template('search.html', user=current_user, results=search, searchterm=searchterm)


@views.route('/user/<int:userid>')
def user(userid):
  """
  This prints user information
  """

  user = User.query.get_or_404(userid)

  return render_template('user.html', userdetails=user, user=current_user)


@views.route('/dashboard/<int:user_id>', methods=['GET', 'POST'])
@login_required
def dashboard(user_id):
  """
  This is the base dashboard page, users must be logged in to access
  """

  if current_user.id != user_id:
    abort(403)

  user = User.query.filter_by(id=user_id).first()

  return render_template("dashboard/dashboard.html", user=user)

@views.route('/dashboard/booksborrowed/<int:user_id>')
@login_required
def borrowed(user_id):
  """
  This is borrowed page, it takes the current user id and checks if they have books borrowed under their account and prints it out on the page.
  """
  if current_user.id != user_id:
    abort(403)

  borrower = Borrower.query.filter_by(user_id=user_id).first()

  if not borrower:
    flash('Enter personal details!', category='error')
    return redirect(url_for('views.infoedit', user_id=current_user.id))
  else:
    bookslist = db.session.query(Borrowed_book, Book)\
      .filter(Borrowed_book.borrower_id == borrower.id)\
      .filter(Borrowed_book.return_confirm == False)\
      .outerjoin(Borrowed_book, Borrowed_book.book_id == Book.id)\
      .add_columns(Book.id, Book.lender_user_id, Borrowed_book.due_date, Borrowed_book.return_book, Borrowed_book.return_confirm, Book.title, Book.author, Book.lender_username, Borrowed_book.lender_confirm, Borrowed_book.lender_id)\
      .filter(Book.id == Borrowed_book.book_id).all()

  datenow = datetime.today()

  return render_template("dashboard/booksborrowed.html", user=current_user, bookslist=bookslist, datenow=datenow)

@views.route('/dashboard/bookslended/<int:user_id>')
@login_required
def lended(user_id):
  """
  This is my lended page, it takes the current user id and checks if they have books that they've lended on the system and it prints it out on the page. 
  """

  if current_user.id != user_id:
    abort(403)

  books = Book.query.filter_by(lender_user_id=user_id).all()

  return render_template("dashboard/bookslended.html", user=current_user, books=books)

@views.route('/dashboard/bookslended/bookstatus/<int:book_id>')
@login_required
def status(book_id):
  """
  This is my status page, it takes the book id that the user has lended and checks if anyone has requested or is currently borrowing that book. 
  """

  book = Book.query.get_or_404(book_id)


  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\
    .filter(Borrowed_book.return_confirm == False)\
    .outerjoin(Borrowed_book, Borrowed_book.borrower_id==Borrower.id)\
    .add_columns(Borrower.username, Borrower.id, Borrowed_book.borrower_id, Borrowed_book.lender_confirm, Borrowed_book.return_book)\
    .filter(Borrower.id == Borrowed_book.borrower_id)\
    .order_by(Borrowed_book.borrowed_date).all()
  
  if current_user.id != book.lender_user_id:
    abort(403)

  return render_template("dashboard/bookstatus.html", user=current_user, books=book, borrowerlist=borrowerlist)

@views.route('/deny/<int:book_id>/borrower/<int:borrower_id>', methods=['GET', 'POST'])
@login_required
def deny(book_id, borrower_id):
  """
  This allows the lender to deny a user to borrow a book.
  """
  book = Book.query.get_or_404(book_id)

  requests = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\
    .filter(borrower_id == Borrowed_book.borrower_id)\
    .outerjoin(Borrower, Borrower.id==Borrowed_book.borrower_id)\
    .add_columns(Borrower.username, Borrower.id, Borrowed_book.borrower_id, Borrower.fName, Borrower.lName, Borrower.address1, Borrower.city, Borrower.phone, Borrowed_book.lender_confirm)\
    .filter(Borrower.id == Borrowed_book.borrower_id).first()

  if current_user.id != book.lender_user_id:
    abort(403)


  else:
    if request.method == 'POST':
      for borrower in borrowerlist:
        borrower = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

      accept = request.form.get('tcs')

      if borrower.lender_confirm:
        flash('Book already being borrowed.', category='error')
        return redirect(url_for('views.status', book_id=book_id))    

      elif not accept:
        flash('Please read and accept our terms and conditions!', category='error')

      else:
        db.session.delete(requests)
        db.session.commit()

        flash('Successfully deleted! Now returning to dashboard', category='success')
        return redirect(url_for('views.status', book_id=book_id))    

  return render_template("deny.html", user=current_user, book=book, borrowerlist=borrowerlist)



@views.route('/accept/<int:book_id>/borrower/<int:borrower_id>', methods=['GET', 'POST'])
@login_required
def accept(book_id, borrower_id):
  """
  This allows the lender to accept requests, it sets the due date to weeks from hitting the accept button on this page. 
  """
  book = Book.query.get_or_404(book_id)

  requests = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\
    .filter(borrower_id == Borrowed_book.borrower_id)\
    .outerjoin(Borrower, Borrower.id==Borrowed_book.borrower_id)\
    .add_columns(Borrower.username, Borrower.id, Borrowed_book.borrower_id, Borrower.fName, Borrower.lName, Borrower.address1, Borrower.city, Borrower.phone, Borrowed_book.lender_confirm)\
    .filter(Borrower.id == Borrowed_book.borrower_id).first()

  borrower_exists = db.session.query(Borrower, Borrowed_book)\
    .filter(borrower_id == Borrowed_book.borrower_id)\
    .filter(Borrowed_book.lender_confirm == True)\
    .outerjoin(Borrower, Borrower.id==Borrowed_book.borrower_id)\
    .filter(Borrower.id == Borrowed_book.borrower_id).first()

  if current_user.id != book.lender_user_id:
    abort(403)


  else:
    if request.method == 'POST':
      for borrower in borrowerlist:
        borrower = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

      accept = request.form.get('tcs')

      if borrower.lender_confirm:
        flash('Book already being borrowed.', category='error')
        return redirect(url_for('views.status', book_id=book_id))    

      elif borrower_exists:
        flash('Borrower is already at limit (1/1)', category='error')
        return redirect(url_for('views.status', book_id=book_id))    


      elif not accept:
        flash('Please read and accept our terms and conditions!', category='error')

      else:

        requests.lender_confirm = True
        
        requests.borrowed_date = datetime.utcnow()
        
        due_date_set = timedelta(weeks = 2)
        due_date = datetime.utcnow() + due_date_set

        requests.due_date = due_date

        db.session.add(requests)
        db.session.commit()

        flash('Successfully confirmed! Now returning to dashboard', category='success')
        return redirect(url_for('views.status', book_id=book_id))    


  return render_template("accept.html", user=current_user, book=book, borrowerlist=borrowerlist, borrower_exists=borrower_exists)

@views.route('/returned/<int:book_id>/borrower/<int:borrower_id>', methods=['GET', 'POST'])
@login_required
def return_confirm(book_id, borrower_id):
  """
  This allows the lender to confirm that the borrower has returned the book
  """
  book = Book.query.get_or_404(book_id)

  requests = Borrowed_book.query.filter_by(borrower_id=borrower_id).filter_by(book_id=book_id).filter_by(return_confirm = False).first()

  borrowerlist = db.session.query(Borrower, Borrowed_book)\
    .filter(book_id == Borrowed_book.book_id)\

website/templates/dashboard/booksborrowed.html
{% extends "dashboard/dashboardbase.html" %} {% block title %}Books Borrowed{% endblock %}{% block content%}

{%if bookslist%}
<h3 class="fs-4 mt-2">Borrow requests:</h3>
<p>Requests that are gone are denied</p>
<p class="text-warning">You can only borrow one book at a time! But can have mutiple requests.</p>
  {% for book in bookslist %}
    {% if not book.lender_confirm %}
    <div class="container-fluid pt-2 d-grid" id="library"> 
      <div class="row row-cols-sm-1 row-cols-lg-4 row-cols-md-2 g-4 d-flex align-items-center justify-content-sm-center">
        <div class="card col-mb-4 p-0" style="width: 18rem;">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-start pb-2">
              <h5 class="card-title">{{ book.title }}</h5> 
            </div>
            <h6 class="card-subtitle mb-2">{{ book.author }}</h6>
            <h6 class="card-subtitle">Lended by <a class="text-3" href="{{url_for('views.user', userid=book.lender_user_id)}}">{{ book.lender_username }}</a></h6>
          </div>
        </div>
      </div> 
    </div>
    {%endif%}
  {%endfor%}

  <h3 class="fs-4 mt-2">Books borrowing:</h3>
  <p>Books will be removed from this list once the lender has confirmed the book is returned.</p>
  {% for book in bookslist %}
    {% if book.lender_confirm %}
      <div class="container-fluid pt-2 d-grid" id="library" > 
        <div class="row row-cols-sm-1 row-cols-lg-4 row-cols-md-2 g-4 d-flex align-items-center justify-content-sm-center">
          <div class="card col-mb-4 p-0" style="width: 18rem;">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-start pb-1">
                <h5 class="card-title">{{ book.title }}</h5>
              </div>
              <div class="d-flex justify-content-center align-items-start flex-column">
                <h6 class="card-subtitle mb-1">{{ book.author }}</h6>
                <h6 class="card-subtitle mb-3" >Lended by <a class="text-3" href="{{url_for('views.user', userid=book.lender_user_id)}}">{{ book.lender_username }}</a></h6>
                {% if book.due_date.date() < datenow.date() %}
                <h6 class="card-subtitle text-danger"> {{ book.due_date.strftime('Book overdue on: %b %d, %Y') }}</h6>
                {%else%}
                <h6 class="card-subtitle"> {{ book.due_date.strftime('Book due on: %b %d, %Y') }}</h6>
                {% endif %}
              </div>
            </div>
            <div class="d-flex justify-content-center align-items-center gap-3 bg-dark p-1 border border-top-0 rounded-1 border-1 flex-nowrap">
              <a href="{{url_for('views.lenderdetails', book_id=book.id, lender_id=book.lender_id )}}" class="text-decoration-none" data-bs-toggle="tooltip" data-bs-placement="left" title="View {{book.lender_username}} details">
                <button class="btn btn-primary btn-sm" type="button">
                  <i class="bi bi-person-circle"></i>
                  Lender Details
                </button>
              </a>

              {% if not book.return_book%}     
                  <a href="{{url_for('views.returned', book_id=book.id, lender_id=book.lender_id )}}">
                    <button class="btn btn-secondary btn-sm" class="text-decoration-none" data-bs-toggle="tooltip" data-bs-placement="left" title="Tell the lender you've returned the book" type="submit" name="returned" value="returned">
                      <i class="bi bi-arrow-return-right"></i>
                      Return Book
                    </button>
                  </a>
              {%else%}
                <h6 class="pt-2 text-white">Lender notifed</h6>
              {%endif%}
              
            </div>
          </div>
        </div>
      </div>
    {%endif%}
  {%endfor%}

{% else %} 
  <p>No books found</p>
  <button type="button" class="btn btn-primary btn-sm px-4" onclick="window.location.href='/books'">Borrow a Book</button>
{%endif%}


{% endblock %}

website/templates/dashboard/bookslended.html
{% extends "dashboard/dashboardbase.html" %} {% block title %}Books Lended{% endblock %}{% block content%}
{% if books %}
<div class="container-fluid pt-2 d-grid" id="library"> 
  <div class="row row-cols-4 d-flex gy-3 gx-3 align-self-start justify-content-evenly">
  {% for book in books %}
    <div class="card row-mb-4 p-1" style="width: 20rem;">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-start">
          <h5 class="card-title">{{ book.title }}</h5> 
          <a href="{{ url_for('views.edit', book_id=book.id ) }}" class="mb-2" data-bs-toggle="tooltip" data-bs-placement="right" title="Edit">
            <i class="bi bi-pencil-square" style="font-size: 1.425rem; color: #181C1F;"></i>
          </a>
        </div>
        <h6 class="card-subtitle mb-2">{{ book.author }}</h6>
        {% if current_user.id == book.lender_user_id %}
          <a href="{{ url_for('views.status', book_id=book.id)}}" class="text-decoration-none" data-bs-toggle="tooltip" data-bs-placement="left" title="Check borrowers">
            <button class="btn btn-success btn-sm">
              <i class="bi bi-patch-check-fill"></i>             
              Check status
            </button>
          </a>
          <a href="{{ url_for('views.edit', book_id=book.id ) }}" class="px-3" data-bs-toggle="tooltip" data-bs-placement="right" title="Delete">
            <button class="btn btn-warning btn-sm">
              <i class="bi bi-trash3-fill"></i>             
              Delete  
            </button>
          </a>
        {% endif %}  
      </div>
    </div>
  {% endfor %}
  </div>
  {% else %}
  <p>No books found</p>
  <button type="button" class="btn btn-secondary btn-sm px-4" onclick="window.location.href='/lend'">Lend a Book</button>
</div>
{%endif%}

{% endblock %}

website/templates/dashboard/bookstatus.html
{% extends "dashboard/dashboardbase.html" %} {% block title %}Books Lended{% endblock %}{% block content%}
<body>
  <div class="container">
    <h4 class="pt-2 fw-semibold text-dark">{{ books.title }} by <small>{{ books.author }}</small></h4>
    <p>This is where you see all the requests for your book. They are ordered by who requested first. <strong> Only deny a borrower if you have a valid reason</strong>, e.g book returned in a bad condition. Upon accept, your book cannot be requested by other people.</p>
    <p class="text-warning">Borrowers can only borrow 1 book at a time!</p>
    <h5 class="pb-2">Requests/Borrowing:</h5>
    {% if borrowerlist %}
      {% for borrower in borrowerlist %}
        <div class="row row-cols-4 d-flex align-self-md-stretch justify-content-md-evenly flex-nowrap">
          <div class="card col-mb-4 p-0" style="width: 14rem;">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-start pb-1">
                <a href="{{url_for('views.user', userid=borrower.id)}}" data-bs-toggle="tooltip" data-bs-placement="right" title="Account Details">
                  <h6 class="card-title">{{borrower.username}}</h6>
                </a>
              </div>
              {% if not borrower.lender_confirm %}
                <div class="d-flex justify-content-evenly align-items-center">
                  <a href="{{url_for('views.accept', book_id=books.id, borrower_id=borrower.id )}}" data-bs-toggle="tooltip" data-bs-placement="left" title="Accept {{ borrower.username }}">
                    <button class="btn btn-primary btn-sm" type="button">
                      <i class="bi bi-check-circle"></i>
                      Accept
                    </button>
                  </a>

                  <a href="{{url_for('views.deny', book_id=books.id, borrower_id=borrower.id )}}" data-bs-toggle="tooltip" data-bs-placement="left" title="Deny {{ borrower.username }}">
                    <button class="btn btn-secondary btn-sm" type="buttton">
                      <i class="bi bi-x-circle"></i>
                      Deny
                    </button>      
                  </a>
        
                  {% else %}
                    {% if borrower.return_book %}
                    <h6 class="mb-1 card-subtitle">{{borrower.username}} has returned the book. Please confirm below!</h6>
                    {%endif%}
        
                    <p class="mb-1">Being borrowed</p>
                    <a href="{{url_for('views.return_confirm', book_id=books.id, borrower_id=borrower.id )}}" data-bs-toggle="tooltip" data-bs-placement="left" title="Accept {{ borrower.username }}">
                      <button class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-bs-placement="left" title="Did {{ borrower.username }} return {{ books.title }}?" type="button">
                        <i class="bi bi-arrow-return-right"></i>
                        Returned?
                      </button>
                    </a>
                </div>
              {%endif%}
            </div>
          </div>
        </div>
      {% endfor %}    
    {%else%}
      <p>No results found.</p>
    {%endif%}
  </div>
</body>
{%endblock%}

website/templates/dashboard/dashboardbase.html
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">
    
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
    />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <link href="{{ url_for('static', filename='css/style.scss.css') }}"
    rel="stylesheet" type="text/css">
    <link rel="icon" type="image/x-icon" href="/static/images/logo.svg">
    
    <title>Dashboard - {{current_user.username}}</title> 
    
  </head>

  <div class="container-fluid">
    <div class="row flex-nowrap overflow-hidden">
      <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark overflow-hidden" style="width: 237px; height:100vh;">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="{{url_for('views.home')}}"><img src="/static/images/banner.svg" alt="logo-banner"></a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{{url_for('views.home')}}" class="show nav-link text-white" aria-current="page" id="home" data-bs-parent="#menu">
              <i class="bi bi-house" style="font-size:1.1rem; padding-right:0.25rem;"></i>
              Home
            </a>
          </li>
          <li>
            <a href="{{url_for('views.dashboard', user_id=current_user.id)}}" class="nav-link text-white">
              <i class="bi bi-speedometer2"  style="font-size:1.1rem; padding-right:0.25rem;"></i>
              Dashboard
            </a>
          </li>
          <li>
            <a href="{{url_for('views.lended', user_id=current_user.id)}}" class="nav-link text-white">
              <i class="bi bi-book"  style="font-size:1.1rem; padding-right:0.25rem;"></i>
              Books Lended
            </a>
          </li>
          <li>
            <a href="{{url_for('views.borrowed', user_id=current_user.id)}}" class="nav-link text-white" >
              <i class="bi bi-basket" style="font-size:1.1rem; padding-right:0.25rem;"></i>
              Books Borrowed
            </a>
          </li>
        </ul>
        <hr>

        <div class="dropdown">
          <a href="{{url_for('views.account', user_id=current_user.id)}}" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="/static/images/footer.svg" alt="" width="32" height="32" class="rounded-circle me-2 border border-white">
            <strong>{{current_user.username}}</strong>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
            <li><a class="dropdown-item" href="{{url_for('views.account', user_id=current_user.id)}}">Settings</a></li>
            <li><a class="dropdown-item" href="{{url_for('views.user', userid=current_user.id)}}">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Sign out</a></li>
          </ul>
        </div>
      </div>

      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
        <div class="alert alert-danger alert-dismissable d-flex align-items-center fade show fixed-top" role="alert">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </svg>
          {{ message }}
          
          <button type="button" class="btn-close position-absolute top-25 end-0 me-3" data-bs-dismiss="alert" aria-label="Close"></button>     
        </div>
  
        {% else %}
        <div class="alert alert-success alert-dismissable d-flex align-items-center fade show fixed-top" role="alert">
  
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="me-2"
            id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
              <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
          </svg>
          {{ message }}
    
          <button type="button" class="btn-close position-absolute top-25 end-0 me-3" data-bs-dismiss="alert" aria-label="Close"></button> 
        </div>
  
        {% endif %}
        {% endfor %}
        {% endif %}
      {% endwith %}
  
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Welcome {{current_user.username}}!</h1>
        </div>
  

        <h2>{% block title %} {% endblock %}</h2>
        <section>{% block content %} {% endblock %}</section>
  
      </main>

    </div>
  </div>


  <script 
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous">
  </script>

  <script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
  crossorigin="anonymous">
  </script>

  <script 
  src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" 
  integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" 
  crossorigin="anonymous">
  </script>

  <script
  type="text/javascript"
  src="{{ url_for('static', filename='javascript/script.js') }}"
  ></script>

  </body>
</html>